name: sharik
description: Sharik is an open-source, cross-platform solution for sharing files via Wi-Fi or Mobile Hotspot
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 3.2.0+15

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # UI
  bootstrap_icons: ^1.5.0

  lucide_icons: ^0.15.30

  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  intro_slider: ^2.4.3
  responsive_framework: ^0.1.4

  qr_flutter: ^4.0.0
  flutter_markdown: ^0.6.7

  # todo linux support
  wakelock: ^0.5.6

  widget_to_image:
    git: https://github.com/marchellodev/widget_to_image.git


  # UTILS
  http: ^0.13.4

  url_launcher: ^6.0.12
  device_apps: ^2.1.1

#  hive: ^2.0.4
  hive_flutter: ^1.1.0


  intl: ^0.17.0
  collection: ^1.15.0

  # todo implement
  receive_sharing_intent: ^1.4.5



  # Android and IOS
  file_picker: ^4.1.4


  # Desktop
  file_selector: ^0.8.2+1
  file_selector_windows: ^0.0.2+1
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.0.4+1


  # ARCHITECTURE
  provider: ^6.0.1

  # ANALYTICS
  ackee_dart: ^0.0.2




dev_dependencies:
  build_runner: ^2.1.4
  hive_generator: ^1.1.1

  lint: ^1.7.2

  flutter_native_splash: ^1.2.4
  change_app_package_name: ^1.0.0




flutter_native_splash:
  # [Colors.deepPurple.shade400]
  color: "#7E57C2"
  web: false

flutter:
  generate: true
  uses-material-design: false

  assets:
    - assets/
    - assets/slides/
    - assets/flags/
    - google_fonts/Andika/
    - google_fonts/Comfortaa/
    - google_fonts/JetBrains/
    - google_fonts/Poppins/
    - privacy_policy.md
    - tracking_policy.md

