name: sharik
description: Sharik is an open-source, cross-platform solution for sharing files via Wi-Fi or Mobile Hotspot
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 3.2.0+15

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # UI
  bootstrap_icons: ^1.9.1

  lucide_icons: ^0.88.0

  flutter_svg: ^1.1.4
  google_fonts: ^3.0.1
  intro_slider: 3.0.3
  responsive_framework: ^0.2.0

  qr_flutter: ^4.0.0
  flutter_markdown: ^0.6.10+5

  # todo linux support
  wakelock: ^0.6.2

  widget_to_image:
    git: https://github.com/marchellodev/widget_to_image.git


  # UTILS
  http: ^0.13.5

  url_launcher: ^6.1.5
  device_apps: ^2.2.0

#  hive: ^2.0.4
  hive_flutter: ^1.1.0


  intl: ^0.17.0

  # todo implement
  receive_sharing_intent: ^1.4.5



  # Android and IOS
  file_picker: ^5.0.1


  # Desktop
  file_selector: ^0.9.2
  file_selector_windows: ^0.9.1+2
  file_selector_linux: ^0.9.0
  file_selector_macos: ^0.9.0+1


  # ARCHITECTURE
  provider: ^6.0.3

  # ANALYTICS
  ackee_dart: ^0.0.2



dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

  lint: ^1.10.0

  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.11

  archive: ^3.3.1
  xml: ^6.1.0
  color: ^3.0.0



flutter_native_splash:
  # [Colors.deepPurple.shade400]
  color: "#7E57C2"
  web: false

flutter:
  generate: true
  uses-material-design: false

  assets:
    - assets/
    - assets/slides/
    - assets/flags/
    - google_fonts/Andika/
    - google_fonts/Comfortaa/
    - google_fonts/JetBrains/
    - google_fonts/Poppins/
    - privacy_policy.md
    - tracking_policy.md

